### ISSUE TITLE
Allow `@FastGenericNew.FastNew` to be declared `internal`

### ISSUE THREAD

**Issue by Emik03** [Nyrest/FastGenericNew#79]
Hi, thanks for creating this excellent source generator and taking the time to maintain and read this. I'd like to suggest a configuration option to make `FastNew` internal, as exposing the classes publicly both makes tree-shakers less efficient, but also causes namespace conflicts if a consumer also uses the source generator or library. When it comes to utility-based functions such as generic factory methods, I very much want to internalize all of those components because I don't want to force users of my library to have functions that they very likely don't need or intend on having. Thanks!

**Comment by Nyrest** [comment]
This will be a very useful feature! 😀
I will work on it soon
